version: 2
project_name: diffmantic

before:
  hooks:
    - go mod tidy

builds:
  - id: diffmantic
    main: ./cmd/diffm
    binary: diffm
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=1
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-linux-musl
          - CXX=zig c++ -target x86_64-linux-musl
      - goos: linux
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-linux-musl
          - CXX=zig c++ -target aarch64-linux-musl
      - goos: windows
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-windows-gnu
          - CXX=zig c++ -target x86_64-windows-gnu

archives:
  - id: diffmantic-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - man/diffm.1
      - man/diffmantic.1

checksum:
  name_template: "checksums.txt"


release:
  mode: replace
  make_latest: true

brews:
  - name: diffmantic
    repository:
      owner: HarshK97
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/HarshK97/diffmantic"
    description: "Structural, semantic diff engine powered by Tree-sitter"
    license: "MIT"
    install: |
      bin.install "diffm"
      man1.install "man/diffm.1"
      man1.install "man/diffmantic.1"
    test: |
      system "#{bin}/diffm --version"

