package rules

var cRules = &Rules{
	Flattened: []string{
		"string_literal",
		"char_literal",
		"system_lib_string",
		"concatenated_string",
	},
	Ignored: []string{
		"\n",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"?",
		"->",
		"comment",
	},
	Aliased: map[string]string{
		"!":        "unary_operator_literal",
		"!=":       "comparison_operator_literal",
		"#define":  "preproc_def",
		"#elif":    "preproc_elif",
		"#else":    "preproc_else",
		"#endif":   "preproc_endif",
		"#if":      "preproc_if",
		"#ifdef":   "preproc_ifdef",
		"#ifndef":  "preproc_ifndef",
		"#include": "preproc_include",
		"#undef":   "preproc_undef",
		"%":        "arithmetic_operator_literal",
		"%=":       "assignment_operator_literal",
		"&":        "bitwise_operator_literal",
		"&&":       "logical_operator_literal",
		"&=":       "assignment_operator_literal",
		"*":        "arithmetic_operator_literal",
		"*=":       "assignment_operator_literal",
		"+":        "arithmetic_operator_literal",
		"++":       "update_operator_literal",
		"+=":       "assignment_operator_literal",
		"-":        "arithmetic_operator_literal",
		"--":       "update_operator_literal",
		"-=":       "assignment_operator_literal",
		"/":        "arithmetic_operator_literal",
		"/=":       "assignment_operator_literal",
		"<":        "comparison_operator_literal",
		"<<":       "bitwise_operator_literal",
		"<<=":      "assignment_operator_literal",
		"<=":       "comparison_operator_literal",
		"=":        "assignment_operator_literal",
		"==":       "comparison_operator_literal",
		">":        "comparison_operator_literal",
		">=":       "comparison_operator_literal",
		">>":       "bitwise_operator_literal",
		">>=":      "assignment_operator_literal",
		"^":        "bitwise_operator_literal",
		"^=":       "assignment_operator_literal",
		"|":        "bitwise_operator_literal",
		"|=":       "assignment_operator_literal",
		"||":       "logical_operator_literal",
		"~":        "bitwise_operator_literal",
	},
	Scaffolding: []string{
		"translation_unit",
		"compound_statement",
		"declaration_list",
		"field_declaration_list",
		"enumerator_list",
		"parameter_list",
		"argument_list",
		"parenthesized_expression",
		"initializer_list",
		"function_definition",
		"type_definition",
		"struct_specifier",
		"union_specifier",
		"enum_specifier",
		"if_statement",
		"else_clause",
		"for_statement",
		"while_statement",
		"do_statement",
		"switch_statement",
		"case_statement",
		"expression_statement",
		"declaration",
		"init_declarator",
		"field_declaration",
		"parameter_declaration",
		"preproc_include",
		"preproc_def",
		"preproc_function_def",
		"preproc_if",
		"preproc_ifdef",
		"preproc_else",
		"preproc_elif",
	},
	Keywords: []string{
		"struct",
		"union",
		"enum",
		"typedef",
		"auto",
		"register",
		"static",
		"extern",
		"const",
		"volatile",
		"inline",
		"void",
		"char",
		"short",
		"int",
		"long",
		"float",
		"double",
		"signed",
		"unsigned",
		"if",
		"else",
		"switch",
		"case",
		"default",
		"for",
		"while",
		"do",
		"goto",
		"continue",
		"break",
		"return",
		"sizeof",
	},
	Declarations: []string{
		"function_definition",
		"declaration",
		"struct_specifier",
		"union_specifier",
		"enum_specifier",
		"type_definition",
		"parameter_declaration",
		"field_declaration",
	},
	Identifiers: []string{
		"identifier",
	},
	Blocks: []string{
		"compound_statement",
	},
	Pairs: []string{
		"field_designator",
		"initializer_pair",
	},
	EquivalentTypes: [][]string{
		{"struct_specifier", "union_specifier", "enum_specifier"},
		{"for_statement", "while_statement", "do_statement"},
	},
	Comments: []string{
		"comment",
	},
	Calls: []string{
		"call_expression",
	},
}
