package rules

var cppRules = &Rules{
	Flattened: []string{
		"string_literal",
		"char_literal",
		"system_lib_string",
		"concatenated_string",
		"raw_string_literal",
	},
	Ignored: []string{
		"\n",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"->",
		"::",
		"comment",
	},
	Aliased: map[string]string{
		"!":        "unary_operator_literal",
		"!=":       "comparison_operator_literal",
		"#define":  "preproc_def",
		"#elif":    "preproc_elif",
		"#else":    "preproc_else",
		"#endif":   "preproc_endif",
		"#if":      "preproc_if",
		"#ifdef":   "preproc_ifdef",
		"#ifndef":  "preproc_ifndef",
		"#include": "preproc_include",
		"#undef":   "preproc_undef",
		"%":        "arithmetic_operator_literal",
		"%=":       "assignment_operator_literal",
		"&":        "bitwise_operator_literal",
		"&&":       "logical_operator_literal",
		"&=":       "assignment_operator_literal",
		"*":        "arithmetic_operator_literal",
		"*=":       "assignment_operator_literal",
		"+":        "arithmetic_operator_literal",
		"++":       "update_operator_literal",
		"+=":       "assignment_operator_literal",
		"-":        "arithmetic_operator_literal",
		"--":       "update_operator_literal",
		"-=":       "assignment_operator_literal",
		"/":        "arithmetic_operator_literal",
		"/=":       "assignment_operator_literal",
		"<":        "comparison_operator_literal",
		"<<":       "bitwise_operator_literal",
		"<<=":      "assignment_operator_literal",
		"<=":       "comparison_operator_literal",
		"<=>":      "comparison_operator_literal",
		"=":        "assignment_operator_literal",
		"==":       "comparison_operator_literal",
		">":        "comparison_operator_literal",
		">=":       "comparison_operator_literal",
		">>":       "bitwise_operator_literal",
		">>=":      "assignment_operator_literal",
		"?":        "ternary_operator_literal",
		"^":        "bitwise_operator_literal",
		"^=":       "assignment_operator_literal",
		"|":        "bitwise_operator_literal",
		"|=":       "assignment_operator_literal",
		"||":       "logical_operator_literal",
		"~":        "bitwise_operator_literal",
	},
	Scaffolding: []string{
		"translation_unit",
		"compound_statement",
		"declaration_list",
		"field_declaration_list",
		"enumerator_list",
		"parameter_list",
		"argument_list",
		"parenthesized_expression",
		"initializer_list",
		"function_definition",
		"type_definition",
		"struct_specifier",
		"union_specifier",
		"enum_specifier",
		"class_specifier",
		"namespace_definition",
		"template_declaration",
		"template_parameter_list",
		"template_argument_list",
		"if_statement",
		"else_clause",
		"for_statement",
		"for_range_loop",
		"while_statement",
		"do_statement",
		"switch_statement",
		"case_statement",
		"try_statement",
		"catch_clause",
		"lambda_expression",
		"expression_statement",
		"declaration",
		"init_declarator",
		"field_declaration",
		"parameter_declaration",
		"alias_declaration",
		"using_declaration",
		"concept_definition",
		"static_assert_declaration",
		"preproc_include",
		"preproc_def",
		"preproc_function_def",
		"preproc_if",
		"preproc_ifdef",
		"preproc_else",
		"preproc_elif",
	},
	Keywords: []string{
		"class",
		"struct",
		"union",
		"enum",
		"typedef",
		"namespace",
		"template",
		"typename",
		"concept",
		"requires",
		"public",
		"private",
		"protected",
		"virtual",
		"override",
		"final",
		"constexpr",
		"consteval",
		"constinit",
		"explicit",
		"inline",
		"friend",
		"static",
		"extern",
		"mutable",
		"const",
		"volatile",
		"auto",
		"decltype",
		"void",
		"bool",
		"char",
		"wchar_t",
		"char8_t",
		"char16_t",
		"char32_t",
		"short",
		"int",
		"long",
		"float",
		"double",
		"signed",
		"unsigned",
		"if",
		"else",
		"switch",
		"case",
		"default",
		"for",
		"while",
		"do",
		"goto",
		"continue",
		"break",
		"return",
		"try",
		"catch",
		"throw",
		"noexcept",
		"new",
		"delete",
		"using",
		"sizeof",
		"co_await",
		"co_yield",
		"co_return",
	},
	Declarations: []string{
		"function_definition",
		"declaration",
		"class_specifier",
		"struct_specifier",
		"union_specifier",
		"enum_specifier",
		"type_definition",
		"namespace_definition",
		"template_declaration",
		"concept_definition",
		"parameter_declaration",
		"field_declaration",
	},
	Identifiers: []string{
		"identifier",
		"destructor_name",
		"operator_name",
	},
	Blocks: []string{
		"compound_statement",
	},
	Pairs: []string{
		"field_designator",
		"initializer_pair",
	},
	EquivalentTypes: [][]string{
		{"function_definition", "template_declaration"},
		{"class_specifier", "struct_specifier", "union_specifier", "enum_specifier"},
		{"for_statement", "for_range_loop", "while_statement", "do_statement"},
	},
	Comments: []string{
		"comment",
	},
	Calls: []string{
		"call_expression",
	},
}
