package rules

var golangRules = &Rules{
	Kind: KindCode,
	Flattened: []string{
		"interpreted_string_literal",
		"raw_string_literal",
	},
	Ignored: []string{
		"\n",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"comment",
	},
	Aliased: map[string]string{
		"!":   "unary_operator_literal",
		"!=":  "comparison_operator_literal",
		"%":   "arithmetic_operator_literal",
		"%=":  "assignment_operator_literal",
		"&":   "bitwise_operator_literal",
		"&&":  "logical_operator_literal",
		"&=":  "assignment_operator_literal",
		"&^":  "bitwise_operator_literal",
		"&^=": "assignment_operator_literal",
		"*":   "arithmetic_operator_literal",
		"*=":  "assignment_operator_literal",
		"+":   "arithmetic_operator_literal",
		"++":  "update_operator_literal",
		"+=":  "assignment_operator_literal",
		"-":   "arithmetic_operator_literal",
		"--":  "update_operator_literal",
		"-=":  "assignment_operator_literal",
		"/":   "arithmetic_operator_literal",
		"/=":  "assignment_operator_literal",
		":=":  "assignment_operator_literal",
		"<":   "comparison_operator_literal",
		"<-":  "channel_operator_literal",
		"<<":  "bitwise_operator_literal",
		"<<=": "assignment_operator_literal",
		"<=":  "comparison_operator_literal",
		"=":   "assignment_operator_literal",
		"==":  "comparison_operator_literal",
		">":   "comparison_operator_literal",
		">=":  "comparison_operator_literal",
		">>":  "bitwise_operator_literal",
		">>=": "assignment_operator_literal",
		"^":   "bitwise_operator_literal",
		"^=":  "assignment_operator_literal",
		"|":   "bitwise_operator_literal",
		"|=":  "assignment_operator_literal",
		"||":  "logical_operator_literal",
	},
	Scaffolding: []string{
		"source_file",
		"block",
		"argument_list",
		"parameter_list",
		"parenthesized_expression",
		"expression_list",
		"literal_value",
		"import_spec_list",
		"function_declaration",
		"method_declaration",
		"if_statement",
		"for_statement",
		"expression_switch_statement",
		"type_switch_statement",
		"select_statement",
		"communication_case",
		"default_case",
		"expression_case",
		"type_case",
	},
	Keywords: []string{
		"package",
		"import",
		"func",
		"var",
		"const",
		"type",
		"struct",
		"interface",
		"if",
		"else",
		"switch",
		"case",
		"default",
		"for",
		"range",
		"return",
		"break",
		"continue",
		"goto",
		"defer",
		"go",
		"select",
		"map",
		"chan",
	},
	Declarations: []string{
		"function_declaration",
		"method_declaration",
		"type_declaration",
		"type_spec",
		"type_alias",
		"field_declaration",
		"const_declaration",
		"var_declaration",
	},
	Identifiers: []string{
		"identifier",
		"field_identifier",
		"type_identifier",
		"package_identifier",
	},
	Blocks: []string{
		"block",
	},
	Wrappers: []string{
		"parenthesized_expression",
		"parenthesized_type",
		"argument_list",
		"type_arguments",
		"type_parameter_list",
		"slice_type",
		"array_type",
		"index_expression",
		"slice_expression",
		"pointer_type",
		"expression_list",
		"var_declaration",
	},
	Pairs: []string{
		"keyed_element",
	},
	Unordered: []string{
		"interface_type",
	},
	EquivalentTypes: [][]string{
		{"function_declaration", "method_declaration"},
		{"short_var_declaration", "assignment_statement", "var_spec"},
	},
	Comments: []string{
		"comment",
	},
	Calls: []string{
		"call_expression",
	},
	ScopedDeclarations: []string{
		"method_declaration",
	},
	Indexed: []string{
		"index_expression",
		"slice_expression",
	},
	LocalVarDeclarations: []string{
		"var_declaration",
		"const_declaration",
		"short_var_declaration",
	},
	ContainerDeclarations: []string{
		"function_declaration",
		"method_declaration",
		"type_declaration",
		"type_spec",
	},
	Closures: []string{
		"func_literal",
	},
	Types: []string{
		"array_type",
		"channel_type",
		"function_type",
		"generic_type",
		"implicit_length_array_type",
		"interface_type",
		"map_type",
		"negated_type",
		"parenthesized_type",
		"pointer_type",
		"qualified_type",
		"slice_type",
		"struct_type",
		"type_identifier",
	},
}
