package rules

var javascriptRules = &Rules{
	Flattened: []string{
		"string",
		"template_string",
	},
	Ignored: []string{
		"\n",
		"_automatic_semicolon",
		"escape_sequence",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"...",
		"?.",
		"@",
		"comment",
		"html_comment",
	},
	Aliased: map[string]string{
		"!":    "unary_operator_literal",
		"!=":   "comparison_operator_literal",
		"!==":  "comparison_operator_literal",
		"%":    "arithmetic_operator_literal",
		"%=":   "assignment_operator_literal",
		"&":    "bitwise_operator_literal",
		"&&":   "logical_operator_literal",
		"&&=":  "assignment_operator_literal",
		"&=":   "assignment_operator_literal",
		"*":    "arithmetic_operator_literal",
		"**":   "arithmetic_operator_literal",
		"**=":  "assignment_operator_literal",
		"*=":   "assignment_operator_literal",
		"+":    "arithmetic_operator_literal",
		"++":   "update_operator_literal",
		"+=":   "assignment_operator_literal",
		"-":    "arithmetic_operator_literal",
		"--":   "update_operator_literal",
		"-=":   "assignment_operator_literal",
		"/":    "arithmetic_operator_literal",
		"/=":   "assignment_operator_literal",
		"<":    "comparison_operator_literal",
		"<<":   "bitwise_operator_literal",
		"<<=":  "assignment_operator_literal",
		"<=":   "comparison_operator_literal",
		"=":    "assignment_operator_literal",
		"==":   "comparison_operator_literal",
		"===":  "comparison_operator_literal",
		"=>":   "arrow",
		">":    "comparison_operator_literal",
		">=":   "comparison_operator_literal",
		">>":   "bitwise_operator_literal",
		">>=":  "assignment_operator_literal",
		">>>":  "bitwise_operator_literal",
		">>>=": "assignment_operator_literal",
		"?":    "ternary_operator_literal",
		"??":   "logical_operator_literal",
		"??=":  "assignment_operator_literal",
		"^":    "bitwise_operator_literal",
		"^=":   "assignment_operator_literal",
		"|":    "bitwise_operator_literal",
		"|=":   "assignment_operator_literal",
		"||":   "logical_operator_literal",
		"||=":  "assignment_operator_literal",
		"~":    "bitwise_operator_literal",
	},
	Scaffolding: []string{
		"program",
		"statement_block",
		"arguments",
		"formal_parameters",
		"expression_statement",
		"variable_declaration",
		"lexical_declaration",
		"using_declaration",
		"variable_declarator",
		"function_declaration",
		"function_expression",
		"arrow_function",
		"method_definition",
		"class_declaration",
		"class_body",
		"if_statement",
		"else_clause",
		"for_statement",
		"for_in_statement",
		"while_statement",
		"do_statement",
		"switch_statement",
		"switch_body",
		"switch_case",
		"switch_default",
		"try_statement",
		"catch_clause",
		"finally_clause",
		"return_statement",
		"object",
		"object_pattern",
		"array",
		"array_pattern",
		"pair",
		"export_statement",
		"import_statement",
		"jsx_element",
		"jsx_opening_element",
		"jsx_closing_element",
		"jsx_self_closing_element",
		"jsx_attribute",
		"jsx_expression",
	},
	Keywords: []string{
		"function",
		"const",
		"let",
		"var",
		"class",
		"extends",
		"import",
		"export",
		"default",
		"from",
		"as",
		"if",
		"else",
		"switch",
		"case",
		"for",
		"while",
		"do",
		"return",
		"break",
		"continue",
		"yield",
		"async",
		"await",
		"try",
		"catch",
		"finally",
		"throw",
		"new",
		"this",
		"super",
		"typeof",
		"instanceof",
		"void",
		"delete",
		"in",
		"of",
	},
	Declarations: []string{
		"function_declaration",
		"generator_function_declaration",
		"class_declaration",
		"method_definition",
		"variable_declaration",
		"lexical_declaration",
		"field_definition",
	},
	Identifiers: []string{
		"identifier",
		"private_property_identifier",
	},
	Blocks: []string{
		"statement_block",
	},
	Wrappers: []string{
		"parenthesized_expression",
		"subscript_expression",
		"array",
		"array_pattern",
		"object_pattern",
		"arguments",
		"formal_parameters",
	},
	Pairs: []string{
		"pair",
		"pair_pattern",
	},
	Unordered: []string{
		"object",
		"object_pattern",
	},
	EquivalentTypes: [][]string{
		{"function_declaration", "function_expression", "arrow_function", "generator_function_declaration", "generator_function"},
		{"lexical_declaration", "variable_declaration"},
		{"for_statement", "for_in_statement"},
	},
	Comments: []string{
		"comment",
		"html_comment",
	},
	Calls: []string{
		"call_expression",
	},
}
