package rules

var javaRules = &Rules{
	Flattened: []string{
		"string_literal",
		"character_literal",
	},
	Ignored: []string{
		"\n",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"->",
		"::",
		"line_comment",
		"block_comment",
	},
	Aliased: map[string]string{
		"!":    "unary_operator_literal",
		"!=":   "comparison_operator_literal",
		"%":    "arithmetic_operator_literal",
		"%=":   "assignment_operator_literal",
		"&":    "bitwise_operator_literal",
		"&&":   "logical_operator_literal",
		"&=":   "assignment_operator_literal",
		"*":    "arithmetic_operator_literal",
		"*=":   "assignment_operator_literal",
		"+":    "arithmetic_operator_literal",
		"++":   "update_operator_literal",
		"+=":   "assignment_operator_literal",
		"-":    "arithmetic_operator_literal",
		"--":   "update_operator_literal",
		"-=":   "assignment_operator_literal",
		"/":    "arithmetic_operator_literal",
		"/=":   "assignment_operator_literal",
		"<":    "comparison_operator_literal",
		"<<":   "bitwise_operator_literal",
		"<<=":  "assignment_operator_literal",
		"<=":   "comparison_operator_literal",
		"=":    "assignment_operator_literal",
		"==":   "comparison_operator_literal",
		">":    "comparison_operator_literal",
		">=":   "comparison_operator_literal",
		">>":   "bitwise_operator_literal",
		">>=":  "assignment_operator_literal",
		">>>":  "bitwise_operator_literal",
		">>>=": "assignment_operator_literal",
		"?":    "ternary_operator_literal",
		"^":    "bitwise_operator_literal",
		"^=":   "assignment_operator_literal",
		"|":    "bitwise_operator_literal",
		"|=":   "assignment_operator_literal",
		"||":   "logical_operator_literal",
		"~":    "bitwise_operator_literal",
	},
	Scaffolding: []string{
		"program",
		"package_declaration",
		"import_declaration",
		"class_declaration",
		"interface_declaration",
		"enum_declaration",
		"record_declaration",
		"annotation_type_declaration",
		"method_declaration",
		"constructor_declaration",
		"field_declaration",
		"constant_declaration",
		"enum_constant",
		"block",
		"constructor_body",
		"class_body",
		"interface_body",
		"enum_body",
		"enum_body_declarations",
		"annotation_type_body",
		"formal_parameters",
		"formal_parameter",
		"spread_parameter",
		"argument_list",
		"type_arguments",
		"type_parameters",
		"parenthesized_expression",
		"array_initializer",
		"element_value_array_initializer",
		"switch_block",
		"switch_label",
		"switch_rule",
		"if_statement",
		"for_statement",
		"enhanced_for_statement",
		"while_statement",
		"do_statement",
		"switch_expression",
		"try_statement",
		"try_with_resources_statement",
		"resource_specification",
		"catch_clause",
		"finally_clause",
		"local_variable_declaration",
		"expression_statement",
		"lambda_expression",
	},
	Keywords: []string{
		"class",
		"interface",
		"enum",
		"record",
		"extends",
		"implements",
		"public",
		"private",
		"protected",
		"static",
		"final",
		"abstract",
		"synchronized",
		"volatile",
		"transient",
		"native",
		"strictfp",
		"void",
		"boolean",
		"byte",
		"short",
		"int",
		"long",
		"char",
		"float",
		"double",
		"if",
		"else",
		"switch",
		"case",
		"default",
		"for",
		"while",
		"do",
		"break",
		"continue",
		"return",
		"yield",
		"try",
		"catch",
		"finally",
		"throw",
		"throws",
		"new",
		"this",
		"super",
		"instanceof",
		"var",
		"package",
		"import",
	},
	Declarations: []string{
		"class_declaration",
		"interface_declaration",
		"enum_declaration",
		"record_declaration",
		"method_declaration",
		"constructor_declaration",
		"annotation_type_declaration",
		"module_declaration",
		"package_declaration",
		"local_variable_declaration",
		"field_declaration",
	},
	Identifiers: []string{
		"identifier",
	},
	Blocks: []string{
		"block",
		"constructor_body",
	},
	Wrappers: []string{
		"parenthesized_expression",
		"type_arguments",
		"type_parameters",
		"array_type",
		"generic_type",
		"cast_expression",
		"argument_list",
		"formal_parameters",
	},
	Pairs: []string{
		"element_value_pair",
	},
	Unordered: []string{
		"annotation",
	},
	EquivalentTypes: [][]string{
		{"method_declaration", "constructor_declaration", "compact_constructor_declaration"},
		{"class_declaration", "interface_declaration", "record_declaration", "enum_declaration", "annotation_type_declaration"},
		{"for_statement", "enhanced_for_statement", "while_statement", "do_statement"},
	},
	Comments: []string{
		"line_comment",
		"block_comment",
	},
	Calls: []string{
		"method_invocation",
		"explicit_constructor_invocation",
	},
}
