package rules

var luaRules = &Rules{
	Flattened: []string{
		"string",
	},
	Ignored: []string{
		"\n",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"::",
		"comment",
	},
	Aliased: map[string]string{
		"#":   "length_operator_literal",
		"%":   "arithmetic_operator_literal",
		"&":   "bitwise_operator_literal",
		"*":   "arithmetic_operator_literal",
		"+":   "arithmetic_operator_literal",
		"-":   "arithmetic_operator_literal",
		"..":  "concat_operator_literal",
		"/":   "arithmetic_operator_literal",
		"//":  "arithmetic_operator_literal",
		"<":   "comparison_operator_literal",
		"<<":  "bitwise_operator_literal",
		"<=":  "comparison_operator_literal",
		"=":   "assignment_operator_literal",
		"==":  "comparison_operator_literal",
		">":   "comparison_operator_literal",
		">=":  "comparison_operator_literal",
		">>":  "bitwise_operator_literal",
		"^":   "arithmetic_operator_literal",
		"and": "logical_operator_literal",
		"not": "unary_operator_literal",
		"or":  "logical_operator_literal",
		"|":   "bitwise_operator_literal",
		"~":   "bitwise_operator_literal",
		"~=":  "comparison_operator_literal",
	},
	Scaffolding: []string{
		"chunk",
		"block",
		"arguments",
		"parameters",
		"parenthesized_expression",
		"expression_list",
		"variable_list",
		"table_constructor",
		"field",
		"function_declaration",
		"function_definition",
		"if_statement",
		"elseif_statement",
		"else_statement",
		"for_statement",
		"for_generic_clause",
		"for_numeric_clause",
		"while_statement",
		"repeat_statement",
		"do_statement",
		"assignment_statement",
		"variable_declaration",
		"return_statement",
		"label_statement",
		"goto_statement",
	},
	Keywords: []string{
		"function",
		"local",
		"return",
		"if",
		"else",
		"elseif",
		"then",
		"end",
		"for",
		"in",
		"do",
		"while",
		"repeat",
		"until",
		"break",
		"goto",
		"and",
		"or",
		"not",
		"true",
		"false",
		"nil",
	},
	Declarations: []string{
		"function_declaration",
		"function_definition",
		"variable_declaration",
	},
	Identifiers: []string{
		"identifier",
	},
	Blocks: []string{
		"block",
	},
	Pairs: []string{
		"field",
	},
	EquivalentTypes: [][]string{
		{"function_declaration", "function_definition", "variable_declaration"},
		{"assignment_statement", "variable_declaration"},
		{"for_statement", "while_statement", "repeat_statement"},
		{"if_statement", "elseif_statement"},
	},
	Comments: []string{
		"comment",
	},
	Calls: []string{
		"function_call",
	},
}
