package rules

var phpRules = &Rules{
	Kind: KindCode,
	Flattened: []string{
		"string",
		"encapsed_string",
		"heredoc",
		"nowdoc",
		"integer",
		"float",
		"boolean",
	},
	Ignored: []string{
		"\n",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"->",
		"?->",
		"::",
		"comment",
	},
	Aliased: map[string]string{
		"!":   "unary_operator_literal",
		"!=":  "comparison_operator_literal",
		"!==": "comparison_operator_literal",
		"%":   "arithmetic_operator_literal",
		"%=":  "assignment_operator_literal",
		"&&":  "logical_operator_literal",
		"&=":  "assignment_operator_literal",
		"*":   "arithmetic_operator_literal",
		"**":  "arithmetic_operator_literal",
		"**=": "assignment_operator_literal",
		"*=":  "assignment_operator_literal",
		"+":   "arithmetic_operator_literal",
		"++":  "update_operator_literal",
		"+=":  "assignment_operator_literal",
		"-":   "arithmetic_operator_literal",
		"--":  "update_operator_literal",
		"-=":  "assignment_operator_literal",
		".=":  "assignment_operator_literal",
		"/":   "arithmetic_operator_literal",
		"/=":  "assignment_operator_literal",
		"<":   "comparison_operator_literal",
		"<<=": "assignment_operator_literal",
		"<=":  "comparison_operator_literal",
		"<=>": "comparison_operator_literal",
		"<>":  "comparison_operator_literal",
		"=":   "assignment_operator_literal",
		"==":  "comparison_operator_literal",
		"===": "comparison_operator_literal",
		">":   "comparison_operator_literal",
		">=":  "comparison_operator_literal",
		">>=": "assignment_operator_literal",
		"?":   "ternary_operator_literal",
		"??":  "null_coalescing_operator_literal",
		"??=": "assignment_operator_literal",
		"^=":  "assignment_operator_literal",
		"and": "logical_operator_literal",
		"or":  "logical_operator_literal",
		"xor": "logical_operator_literal",
		"|=":  "assignment_operator_literal",
		"||":  "logical_operator_literal",
	},
	Scaffolding: []string{
		"program",
		"compound_statement",
		"statement",
		"expression_statement",
		"declaration_list",
		"function_definition",
		"method_declaration",
		"class_declaration",
		"interface_declaration",
		"trait_declaration",
		"enum_declaration",
		"if_statement",
		"for_statement",
		"foreach_statement",
		"while_statement",
		"do_statement",
		"switch_statement",
		"try_statement",
		"catch_clause",
		"finally_clause",
		"match_expression",
		"formal_parameters",
		"arguments",
		"array_creation_expression",
		"property_declaration",
		"const_declaration",
		"use_declaration",
		"namespace_definition",
		"namespace_use_declaration",
	},
	Keywords: []string{
		"function",
		"fn",
		"class",
		"interface",
		"trait",
		"enum",
		"extends",
		"implements",
		"public",
		"private",
		"protected",
		"static",
		"final",
		"abstract",
		"readonly",
		"const",
		"var",
		"use",
		"namespace",
		"if",
		"elseif",
		"else",
		"switch",
		"case",
		"default",
		"for",
		"foreach",
		"while",
		"do",
		"return",
		"break",
		"continue",
		"yield",
		"try",
		"catch",
		"finally",
		"throw",
		"new",
		"clone",
		"match",
		"goto",
		"declare",
		"global",
		"instanceof",
		"insteadof",
		"as",
		"and",
		"or",
		"xor",
	},
	Declarations: []string{
		"function_definition",
		"method_declaration",
		"class_declaration",
		"interface_declaration",
		"trait_declaration",
		"enum_declaration",
		"namespace_definition",
		"property_declaration",
		"const_declaration",
	},
	Identifiers: []string{
		"name",
		"variable_name",
	},
	Blocks: []string{
		"compound_statement",
	},
	Wrappers: []string{
		"parenthesized_expression",
		"array_creation_expression",
		"subscript_expression",
		"arguments",
		"formal_parameters",
	},
	Pairs: []string{
		"pair",
		"array_element_initializer",
	},
	Unordered: []string{
		"array_creation_expression",
		"attribute_group",
		"attribute_list",
	},
	EquivalentTypes: [][]string{
		{"function_definition", "anonymous_function", "arrow_function", "method_declaration"},
		{"class_declaration", "interface_declaration", "trait_declaration", "enum_declaration"},
		{"for_statement", "foreach_statement", "while_statement", "do_statement"},
		{"if_statement", "else_if_clause"},
	},
	Comments: []string{
		"comment",
	},
	Calls: []string{
		"function_call_expression",
		"member_call_expression",
		"scoped_call_expression",
		"nullsafe_member_call_expression",
	},
	Indexed: []string{
		"subscript_expression",
	},
	LocalVarDeclarations: []string{
		"const_declaration",
	},
	ContainerDeclarations: []string{
		"function_definition",
		"method_declaration",
		"class_declaration",
		"interface_declaration",
		"trait_declaration",
		"enum_declaration",
	},
	Closures: []string{
		"anonymous_function",
		"arrow_function",
	},
	Types: []string{
		"bottom_type",
		"cast_type",
		"disjunctive_normal_form_type",
		"intersection_type",
		"named_type",
		"optional_type",
		"primitive_type",
		"union_type",
	},
	JumpStatements: []string{
		"return_statement",
		"break_statement",
		"continue_statement",
		"goto_statement",
		"throw_expression",
		"yield_expression",
	},
	TerminalCalls: []string{
		"exit",
		"die",
	},
	DelimitedContainers: []string{
		"arguments",
		"array_creation_expression",
		"formal_parameters",
	},
	CaseClauses: []string{
		"case_statement",
		"default_statement",
	},
	Expressions: []string{
		"array_creation_expression",
		"assignment_expression",
		"augmented_assignment_expression",
		"binary_expression",
		"cast_expression",
		"class_constant_access_expression",
		"clone_expression",
		"conditional_expression",
		"error_suppression_expression",
		"expression",
		"function_call_expression",
		"include_expression",
		"include_once_expression",
		"match_conditional_expression",
		"match_default_expression",
		"match_expression",
		"member_access_expression",
		"member_call_expression",
		"nullsafe_member_access_expression",
		"nullsafe_member_call_expression",
		"object_creation_expression",
		"parenthesized_expression",
		"primary_expression",
		"reference_assignment_expression",
		"require_expression",
		"require_once_expression",
		"scoped_call_expression",
		"scoped_property_access_expression",
		"sequence_expression",
		"shell_command_expression",
		"subscript_expression",
		"throw_expression",
		"unary_op_expression",
		"update_expression",
		"yield_expression",
	},
}
