package rules

var pythonRules = &Rules{
	Kind: KindCode,
	Flattened: []string{
		"string",
		"concatenated_string",
	},
	Ignored: []string{
		"_newline",
		"_indent",
		"_dedent",
		"line_continuation",
		"escape_sequence",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"->",
		"@",
		"comment",
	},
	Aliased: map[string]string{
		"!=":                   "comparison_operator_literal",
		"%":                    "arithmetic_operator_literal",
		"%=":                   "assignment_operator_literal",
		"&":                    "bitwise_operator_literal",
		"&=":                   "assignment_operator_literal",
		"*":                    "arithmetic_operator_literal",
		"**":                   "arithmetic_operator_literal",
		"**=":                  "assignment_operator_literal",
		"*=":                   "assignment_operator_literal",
		"+":                    "arithmetic_operator_literal",
		"+=":                   "assignment_operator_literal",
		"-":                    "arithmetic_operator_literal",
		"-=":                   "assignment_operator_literal",
		"/":                    "arithmetic_operator_literal",
		"//":                   "arithmetic_operator_literal",
		"//=":                  "assignment_operator_literal",
		"/=":                   "assignment_operator_literal",
		":=":                   "assignment_operator_literal",
		"<":                    "comparison_operator_literal",
		"<<":                   "bitwise_operator_literal",
		"<<=":                  "assignment_operator_literal",
		"<=":                   "comparison_operator_literal",
		"<>":                   "comparison_operator_literal",
		"=":                    "assignment_operator_literal",
		"==":                   "comparison_operator_literal",
		">":                    "comparison_operator_literal",
		">=":                   "comparison_operator_literal",
		">>":                   "bitwise_operator_literal",
		">>=":                  "assignment_operator_literal",
		"@=":                   "assignment_operator_literal",
		"^":                    "bitwise_operator_literal",
		"^=":                   "assignment_operator_literal",
		"and":                  "logical_operator_literal",
		"augmented_assignment": "assignment",
		"for_in_clause":        "for_statement",
		"is":                   "comparison_operator_literal",
		"is not":               "comparison_operator_literal",
		"not":                  "unary_operator_literal",
		"not in":               "comparison_operator_literal",
		"or":                   "logical_operator_literal",
		"|":                    "bitwise_operator_literal",
		"|=":                   "assignment_operator_literal",
		"~":                    "bitwise_operator_literal",
	},
	Scaffolding: []string{
		"module",
		"block",
		"argument_list",
		"parameters",
		"lambda_parameters",
		"parenthesized_expression",
		"expression_statement",
		"expression_list",
		"pattern_list",
		"list",
		"dictionary",
		"set",
		"tuple",
		"list_comprehension",
		"dictionary_comprehension",
		"set_comprehension",
		"generator_expression",
		"for_in_clause",
		"if_clause",
		"try_statement",
		"except_clause",
		"finally_clause",
		"function_definition",
		"class_definition",
		"with_statement",
		"with_clause",
		"for_statement",
		"while_statement",
		"if_statement",
		"elif_clause",
		"else_clause",
		"match_statement",
		"case_clause",
		"decorated_definition",
		"import_statement",
		"import_from_statement",
		"assert_statement",
		"global_statement",
		"nonlocal_statement",
		"type_alias_statement",
		"except_group_clause",
		"return_statement",
		"raise_statement",
		"pass_statement",
		"break_statement",
		"continue_statement",
	},
	Keywords: []string{
		"def",
		"class",
		"import",
		"from",
		"as",
		"if",
		"elif",
		"else",
		"for",
		"while",
		"in",
		"not",
		"and",
		"or",
		"is",
		"return",
		"yield",
		"break",
		"continue",
		"pass",
		"try",
		"except",
		"finally",
		"raise",
		"with",
		"async",
		"await",
		"global",
		"nonlocal",
		"assert",
		"lambda",
		"match",
		"case",
	},
	Declarations: []string{
		"function_definition",
		"class_definition",
		"type_alias_statement",
	},
	Identifiers: []string{
		"identifier",
		"type",
	},
	Blocks: []string{
		"block",
	},
	Wrappers: []string{
		"parenthesized_expression",
		"argument_list",
		"parameters",
		"list",
		"tuple",
		"set",
		"dictionary",
		"generator_expression",
		"list_comprehension",
		"dictionary_comprehension",
		"set_comprehension",
	},
	Pairs: []string{
		"pair",
		"keyword_argument",
	},
	Unordered: []string{
		"dictionary",
		"set",
	},
	EquivalentTypes: [][]string{
		{"for_statement", "for_in_clause", "while_statement"},
		{"if_statement", "elif_clause"},
	},
	Comments: []string{
		"comment",
	},
	Calls: []string{
		"call",
	},
	Indexed: []string{
		"subscript",
	},
	LocalVarDeclarations: []string{
		"global_statement",
		"nonlocal_statement",
	},
	ContainerDeclarations: []string{
		"function_definition",
		"class_definition",
	},
	Closures: []string{
		"lambda",
	},
	Types: []string{
		"constrained_type",
		"generic_type",
		"member_type",
		"splat_type",
		"union_type",
	},
	JumpStatements: []string{
		"return_statement",
		"raise_statement",
		"break_statement",
		"continue_statement",
		"pass_statement",
	},
	TerminalCalls: []string{
		"sys.exit",
		"os._exit",
		"exit",
		"quit",
	},
	DelimitedContainers: []string{
		"argument_list",
		"dictionary",
		"list",
		"parameters",
		"tuple",
		"set",
	},
}
