package rules

var rubyRules = &Rules{
	Flattened: []string{
		"string",
		"string_content",
		"heredoc_body",
		"regex",
		"integer",
		"float",
		"simple_symbol",
		"identifier",
		"instance_variable",
		"class_variable",
		"global_variable",
		"constant",
	},
	Ignored: []string{
		"\n",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		"::",
		".",
		"->",
		"|",
		"=>",
		"comment",
	},
	Aliased: map[string]string{
		"!":   "unary_operator_literal",
		"!=":  "comparison_operator_literal",
		"!~":  "comparison_operator_literal",
		"%":   "arithmetic_operator_literal",
		"%=":  "assignment_operator_literal",
		"&":   "bitwise_operator_literal",
		"&&":  "logical_operator_literal",
		"&&=": "assignment_operator_literal",
		"&=":  "assignment_operator_literal",
		"*":   "arithmetic_operator_literal",
		"**":  "arithmetic_operator_literal",
		"**=": "assignment_operator_literal",
		"*=":  "assignment_operator_literal",
		"+":   "arithmetic_operator_literal",
		"+=":  "assignment_operator_literal",
		"-":   "arithmetic_operator_literal",
		"-=":  "assignment_operator_literal",
		"/":   "arithmetic_operator_literal",
		"/=":  "assignment_operator_literal",
		"<":   "comparison_operator_literal",
		"<<":  "bitwise_operator_literal",
		"<<=": "assignment_operator_literal",
		"<=":  "comparison_operator_literal",
		"<=>": "comparison_operator_literal",
		"=":   "assignment_operator_literal",
		"==":  "comparison_operator_literal",
		"===": "comparison_operator_literal",
		"=~":  "comparison_operator_literal",
		">":   "comparison_operator_literal",
		">=":  "comparison_operator_literal",
		">>":  "bitwise_operator_literal",
		">>=": "assignment_operator_literal",
		"?":   "ternary_operator_literal",
		"^":   "bitwise_operator_literal",
		"^=":  "assignment_operator_literal",
		"|":   "bitwise_operator_literal",
		"|=":  "assignment_operator_literal",
		"||":  "logical_operator_literal",
		"||=": "assignment_operator_literal",
		"~":   "bitwise_operator_literal",
	},
	Scaffolding: []string{
		"program",
		"body_statement",
		"method",
		"singleton_method",
		"class",
		"module",
		"if",
		"unless",
		"elsif",
		"else",
		"while",
		"until",
		"for",
		"case",
		"when",
		"begin",
		"rescue",
		"ensure",
		"call",
		"argument_list",
		"method_parameters",
		"block_parameters",
		"do_block",
		"block",
		"assignment",
		"operator_assignment",
		"hash",
		"array",
		"pair",
	},
	Keywords: []string{
		"def",
		"class",
		"module",
		"if",
		"unless",
		"elsif",
		"else",
		"case",
		"when",
		"while",
		"until",
		"for",
		"do",
		"begin",
		"rescue",
		"ensure",
		"end",
		"return",
		"yield",
		"break",
		"next",
		"redo",
		"retry",
		"alias",
		"undef",
		"and",
		"or",
		"not",
		"then",
		"in",
		"self",
		"nil",
		"true",
		"false",
		"super",
	},
	Declarations: []string{
		"method",
		"singleton_method",
		"class",
		"module",
	},
	Identifiers: []string{
		"identifier",
		"constant",
	},
	Blocks: []string{
		"block",
	},
	Pairs: []string{
		"pair",
	},
	Unordered: []string{
		"hash",
		"hash_pattern",
	},
	EquivalentTypes: [][]string{
		{"method", "singleton_method"},
		{"class", "module", "singleton_class"},
		{"if", "unless"},
		{"while", "until", "for"},
	},
	Comments: []string{
		"comment",
	},
	Calls: []string{
		"call",
	},
}
