package rules

var rustRules = &Rules{
	Kind: KindCode,
	Flattened: []string{
		"string_literal",
		"raw_string_literal",
	},
	Ignored: []string{
		"\n",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"->",
		"=>",
		"::",
		"@",
		"line_comment",
		"block_comment",
		"doc_comment",
	},
	Aliased: map[string]string{
		"!":   "unary_operator_literal",
		"!=":  "comparison_operator_literal",
		"%":   "arithmetic_operator_literal",
		"%=":  "assignment_operator_literal",
		"&":   "bitwise_operator_literal",
		"&&":  "logical_operator_literal",
		"&=":  "assignment_operator_literal",
		"*":   "arithmetic_operator_literal",
		"*=":  "assignment_operator_literal",
		"+":   "arithmetic_operator_literal",
		"+=":  "assignment_operator_literal",
		"-":   "arithmetic_operator_literal",
		"-=":  "assignment_operator_literal",
		"..":  "range_operator_literal",
		"...": "range_operator_literal",
		"..=": "range_operator_literal",
		"/":   "arithmetic_operator_literal",
		"/=":  "assignment_operator_literal",
		"<":   "comparison_operator_literal",
		"<<":  "bitwise_operator_literal",
		"<<=": "assignment_operator_literal",
		"<=":  "comparison_operator_literal",
		"=":   "assignment_operator_literal",
		"==":  "comparison_operator_literal",
		">":   "comparison_operator_literal",
		">=":  "comparison_operator_literal",
		">>":  "bitwise_operator_literal",
		">>=": "assignment_operator_literal",
		"?":   "try_operator_literal",
		"^":   "bitwise_operator_literal",
		"^=":  "assignment_operator_literal",
		"|":   "bitwise_operator_literal",
		"|=":  "assignment_operator_literal",
		"||":  "logical_operator_literal",
	},
	Scaffolding: []string{
		"source_file",
		"block",
		"declaration_list",
		"field_declaration_list",
		"ordered_field_declaration_list",
		"enum_variant_list",
		"use_list",
		"type_parameters",
		"type_arguments",
		"parameters",
		"closure_parameters",
		"arguments",
		"parenthesized_expression",
		"tuple_expression",
		"array_expression",
		"struct_expression",
		"field_initializer_list",
		"match_block",
		"match_arm",
		"if_expression",
		"else_clause",
		"while_expression",
		"loop_expression",
		"for_expression",
		"function_item",
		"struct_item",
		"enum_item",
		"trait_item",
		"impl_item",
		"macro_definition",
		"macro_invocation",
		"let_declaration",
		"use_declaration",
		"expression_statement",
		"unsafe_block",
		"async_block",
		"const_block",
		"match_expression",
		"return_expression",
		"break_expression",
		"continue_expression",
		"empty_statement",
	},
	Keywords: []string{
		"fn",
		"let",
		"mut",
		"const",
		"static",
		"struct",
		"enum",
		"union",
		"trait",
		"impl",
		"type",
		"use",
		"mod",
		"pub",
		"crate",
		"self",
		"Super",
		"if",
		"else",
		"match",
		"while",
		"loop",
		"for",
		"in",
		"return",
		"break",
		"continue",
		"async",
		"await",
		"unsafe",
		"where",
		"ref",
		"dyn",
	},
	Declarations: []string{
		"function_item",
		"struct_item",
		"enum_item",
		"union_item",
		"trait_item",
		"impl_item",
		"type_item",
		"mod_item",
		"const_item",
		"static_item",
	},
	Identifiers: []string{
		"identifier",
		"type_identifier",
		"field_identifier",
		"shorthand_field_identifier",
		"scoped_identifier",
	},
	Blocks: []string{
		"block",
	},
	Wrappers: []string{
		"parenthesized_expression",
		"generic_type",
		"type_arguments",
		"array_type",
		"reference_type",
		"tuple_expression",
		"array_expression",
		"index_expression",
		"arguments",
		"parameters",
	},
	Pairs: []string{
		"field_initializer",
		"field_pattern",
	},
	Unordered: []string{
		"use_declaration",
	},
	EquivalentTypes: [][]string{
		{"struct_item", "enum_item", "union_item", "trait_item"},
		{"for_expression", "while_expression", "loop_expression"},
	},
	Comments: []string{
		"line_comment",
		"block_comment",
		"doc_comment",
	},
	Calls: []string{
		"call_expression",
		"macro_invocation",
	},
	Indexed: []string{
		"index_expression",
	},
	LocalVarDeclarations: []string{
		"let_declaration",
	},
	ContainerDeclarations: []string{
		"function_item",
		"struct_item",
		"enum_item",
		"union_item",
		"trait_item",
		"impl_item",
		"mod_item",
		"type_item",
	},
	Closures: []string{
		"closure_expression",
	},
	Types: []string{
		"abstract_type",
		"array_type",
		"associated_type",
		"bounded_type",
		"bracketed_type",
		"dynamic_type",
		"function_type",
		"generic_type",
		"never_type",
		"pointer_type",
		"primitive_type",
		"qualified_type",
		"reference_type",
		"scoped_type_identifier",
		"tuple_type",
		"type_identifier",
		"unit_type",
	},
	JumpStatements: []string{
		"return_expression",
		"break_expression",
		"continue_expression",
		"yield_expression",
	},
	TerminalCalls: []string{
		"std.process.exit",
		"process.exit",
		"panic",
	},
	DelimitedContainers: []string{
		"arguments",
		"array_expression",
		"field_initializer_list",
		"parameters",
		"token_tree",
		"tuple_expression",
	},
	CaseClauses: []string{
		"match_arm",
	},
	Expressions: []string{
		"array_expression",
		"assignment_expression",
		"await_expression",
		"binary_expression",
		"break_expression",
		"call_expression",
		"closure_expression",
		"continue_expression",
		"field_expression",
		"for_expression",
		"if_expression",
		"index_expression",
		"loop_expression",
		"macro_invocation",
		"match_expression",
		"parenthesized_expression",
		"range_expression",
		"reference_expression",
		"return_expression",
		"struct_expression",
		"try_expression",
		"tuple_expression",
		"type_cast_expression",
		"unary_expression",
		"unit_expression",
		"while_expression",
		"yield_expression",
	},
}
