package rules

var rustRules = &Rules{
	Flattened: []string{
		"string_literal",
		"raw_string_literal",
	},
	Ignored: []string{
		"\n",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"?",
		"->",
		"=>",
		"::",
		"@",
		"line_comment",
		"block_comment",
		"doc_comment",
	},
	Aliased: map[string]string{
		"!":   "unary_operator_literal",
		"!=":  "comparison_operator_literal",
		"%":   "arithmetic_operator_literal",
		"%=":  "assignment_operator_literal",
		"&":   "bitwise_operator_literal",
		"&&":  "logical_operator_literal",
		"&=":  "assignment_operator_literal",
		"*":   "arithmetic_operator_literal",
		"*=":  "assignment_operator_literal",
		"+":   "arithmetic_operator_literal",
		"+=":  "assignment_operator_literal",
		"-":   "arithmetic_operator_literal",
		"-=":  "assignment_operator_literal",
		"..":  "range_operator_literal",
		"...": "range_operator_literal",
		"..=": "range_operator_literal",
		"/":   "arithmetic_operator_literal",
		"/=":  "assignment_operator_literal",
		"<":   "comparison_operator_literal",
		"<<":  "bitwise_operator_literal",
		"<<=": "assignment_operator_literal",
		"<=":  "comparison_operator_literal",
		"=":   "assignment_operator_literal",
		"==":  "comparison_operator_literal",
		">":   "comparison_operator_literal",
		">=":  "comparison_operator_literal",
		">>":  "bitwise_operator_literal",
		">>=": "assignment_operator_literal",
		"^":   "bitwise_operator_literal",
		"^=":  "assignment_operator_literal",
		"|":   "bitwise_operator_literal",
		"|=":  "assignment_operator_literal",
		"||":  "logical_operator_literal",
	},
	Scaffolding: []string{
		"source_file",
		"block",
		"declaration_list",
		"field_declaration_list",
		"ordered_field_declaration_list",
		"enum_variant_list",
		"use_list",
		"type_parameters",
		"type_arguments",
		"parameters",
		"closure_parameters",
		"arguments",
		"parenthesized_expression",
		"tuple_expression",
		"array_expression",
		"struct_expression",
		"field_initializer_list",
		"match_block",
		"match_arm",
		"if_expression",
		"else_clause",
		"while_expression",
		"loop_expression",
		"for_expression",
		"function_item",
		"struct_item",
		"enum_item",
		"trait_item",
		"impl_item",
		"macro_definition",
		"macro_invocation",
		"let_declaration",
		"use_declaration",
		"expression_statement",
	},
	Keywords: []string{
		"fn",
		"let",
		"mut",
		"const",
		"static",
		"struct",
		"enum",
		"union",
		"trait",
		"impl",
		"type",
		"use",
		"mod",
		"pub",
		"crate",
		"self",
		"Super",
		"if",
		"else",
		"match",
		"while",
		"loop",
		"for",
		"in",
		"return",
		"break",
		"continue",
		"async",
		"await",
		"unsafe",
		"where",
		"ref",
		"dyn",
	},
	Declarations: []string{
		"function_item",
		"struct_item",
		"enum_item",
		"union_item",
		"trait_item",
		"impl_item",
		"type_item",
		"mod_item",
		"const_item",
		"static_item",
	},
	Identifiers: []string{
		"identifier",
	},
	Blocks: []string{
		"block",
	},
	Pairs: []string{
		"field_initializer",
	},
	Unordered: []string{
		"use_declaration",
	},
	EquivalentTypes: [][]string{
		{"struct_item", "enum_item", "union_item", "trait_item"},
		{"for_expression", "while_expression", "loop_expression"},
	},
	Comments: []string{
		"line_comment",
		"block_comment",
		"doc_comment",
	},
	Calls: []string{
		"call_expression",
		"macro_invocation",
	},
}
