package rules

var typescriptRules = &Rules{
	Kind: KindCode,
	Flattened: []string{
		"string",
		"template_string",
	},
	Ignored: []string{
		"\n",
		"_automatic_semicolon",
		"escape_sequence",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"...",
		"?.",
		"comment",
		"html_comment",
	},
	Aliased: map[string]string{
		"!":    "unary_operator_literal",
		"!=":   "comparison_operator_literal",
		"!==":  "comparison_operator_literal",
		"%":    "arithmetic_operator_literal",
		"%=":   "assignment_operator_literal",
		"&":    "bitwise_operator_literal",
		"&&":   "logical_operator_literal",
		"&&=":  "assignment_operator_literal",
		"&=":   "assignment_operator_literal",
		"*":    "arithmetic_operator_literal",
		"**":   "arithmetic_operator_literal",
		"**=":  "assignment_operator_literal",
		"*=":   "assignment_operator_literal",
		"+":    "arithmetic_operator_literal",
		"++":   "update_operator_literal",
		"+=":   "assignment_operator_literal",
		"-":    "arithmetic_operator_literal",
		"--":   "update_operator_literal",
		"-=":   "assignment_operator_literal",
		"/":    "arithmetic_operator_literal",
		"/=":   "assignment_operator_literal",
		"<":    "comparison_operator_literal",
		"<<":   "bitwise_operator_literal",
		"<<=":  "assignment_operator_literal",
		"<=":   "comparison_operator_literal",
		"=":    "assignment_operator_literal",
		"==":   "comparison_operator_literal",
		"===":  "comparison_operator_literal",
		"=>":   "arrow",
		">":    "comparison_operator_literal",
		">=":   "comparison_operator_literal",
		">>":   "bitwise_operator_literal",
		">>=":  "assignment_operator_literal",
		">>>":  "bitwise_operator_literal",
		">>>=": "assignment_operator_literal",
		"?":    "ternary_operator_literal",
		"??":   "logical_operator_literal",
		"??=":  "assignment_operator_literal",
		"^":    "bitwise_operator_literal",
		"^=":   "assignment_operator_literal",
		"|":    "bitwise_operator_literal",
		"|=":   "assignment_operator_literal",
		"||":   "logical_operator_literal",
		"||=":  "assignment_operator_literal",
		"~":    "bitwise_operator_literal",
	},
	Scaffolding: []string{
		"program",
		"statement_block",
		"formal_parameters",
		"arguments",
		"parenthesized_expression",
		"expression_statement",
		"function_declaration",
		"method_definition",
		"arrow_function",
		"class_declaration",
		"class_body",
		"interface_declaration",
		"enum_declaration",
		"enum_body",
		"type_alias_declaration",
		"if_statement",
		"else_clause",
		"for_statement",
		"for_in_statement",
		"while_statement",
		"do_statement",
		"switch_statement",
		"switch_body",
		"switch_case",
		"switch_default",
		"try_statement",
		"catch_clause",
		"finally_clause",
		"return_statement",
		"class_static_block",
		"debugger_statement",
		"empty_statement",
		"labeled_statement",
		"with_statement",
		"import_statement",
		"export_statement",
		"object",
		"array",
		"type_arguments",
		"type_parameters",
	},
	Keywords: []string{
		"function",
		"const",
		"let",
		"var",
		"class",
		"extends",
		"implements",
		"interface",
		"type",
		"namespace",
		"enum",
		"abstract",
		"readonly",
		"private",
		"public",
		"protected",
		"override",
		"import",
		"export",
		"default",
		"from",
		"as",
		"if",
		"else",
		"switch",
		"case",
		"for",
		"while",
		"do",
		"return",
		"break",
		"continue",
		"yield",
		"async",
		"await",
		"try",
		"catch",
		"finally",
		"throw",
		"new",
		"this",
		"super",
		"typeof",
		"instanceof",
		"void",
		"delete",
		"in",
		"of",
		"keyof",
		"infer",
		"is",
		"satisfies",
	},
	Declarations: []string{
		"function_declaration",
		"generator_function_declaration",
		"class_declaration",
		"abstract_class_declaration",
		"interface_declaration",
		"enum_declaration",
		"type_alias_declaration",
		"method_definition",
		"variable_declaration",
		"lexical_declaration",
	},
	Identifiers: []string{
		"identifier",
		"property_identifier",
		"shorthand_property_identifier",
		"nested_identifier",
		"nested_type_identifier",
		"private_property_identifier",
		"property_identifier",
		"shorthand_property_identifier",
		"shorthand_property_identifier_pattern",
		"statement_identifier",
		"type_identifier",
	},
	Blocks: []string{
		"statement_block",
	},
	Wrappers: []string{
		"export_statement",
		"parenthesized_expression",
		"parenthesized_type",
		"type_arguments",
		"type_parameters",
		"array_type",
		"generic_type",
		"object",
		"array",
		"arguments",
		"formal_parameters",
	},
	Pairs: []string{
		"pair",
		"pair_pattern",
		"property_signature",
	},
	Unordered: []string{
		"object",
		"object_type",
		"object_pattern",
		"named_imports",
		"export_clause",
	},
	EquivalentTypes: [][]string{
		{"function_declaration", "function_expression", "arrow_function", "generator_function_declaration", "generator_function"},
		{"method_definition", "method_signature"},
		{"class_declaration", "abstract_class_declaration", "interface_declaration", "type_alias_declaration", "enum_declaration"},
		{"lexical_declaration", "variable_declaration"},
		{"for_statement", "for_in_statement"},
	},
	Comments: []string{
		"comment",
		"html_comment",
	},
	Calls: []string{
		"call_expression",
	},
	Indexed: []string{
		"subscript_expression",
	},
	LocalVarDeclarations: []string{
		"variable_declaration",
		"lexical_declaration",
	},
	ContainerDeclarations: []string{
		"function_declaration",
		"generator_function_declaration",
		"method_definition",
		"class_declaration",
		"interface_declaration",
		"type_alias_declaration",
		"enum_declaration",
		"module",
	},
	Closures: []string{
		"arrow_function",
		"function_expression",
		"function",
	},
	Types: []string{
		"array_type",
		"conditional_type",
		"constructor_type",
		"default_type",
		"existential_type",
		"flow_maybe_type",
		"function_type",
		"generic_type",
		"infer_type",
		"intersection_type",
		"literal_type",
		"lookup_type",
		"nested_type_identifier",
		"object_type",
		"optional_type",
		"parenthesized_type",
		"predefined_type",
		"primary_type",
		"readonly_type",
		"rest_type",
		"template_literal_type",
		"template_type",
		"this_type",
		"tuple_type",
		"type_identifier",
		"union_type",
	},
	JumpStatements: []string{
		"return_statement",
		"break_statement",
		"continue_statement",
		"throw_statement",
		"yield_expression",
	},
	TerminalCalls: []string{
		"process.exit",
	},
	DelimitedContainers: []string{
		"arguments",
		"array",
		"formal_parameters",
		"object",
		"object_pattern",
		"object_type",
	},
	CaseClauses: []string{
		"switch_case",
		"switch_default",
	},
	Expressions: []string{
		"arrow_function",
		"as_expression",
		"assignment_expression",
		"augmented_assignment_expression",
		"await_expression",
		"binary_expression",
		"call_expression",
		"expression",
		"function_expression",
		"instantiation_expression",
		"member_expression",
		"new_expression",
		"non_null_expression",
		"parenthesized_expression",
		"primary_expression",
		"satisfies_expression",
		"sequence_expression",
		"subscript_expression",
		"template_string",
		"ternary_expression",
		"unary_expression",
		"update_expression",
		"yield_expression",
	},
}
