package rules

var zigRules = &Rules{
	Flattened: []string{
		"string",
		"multiline_string",
		"character",
	},
	Ignored: []string{
		"\n",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		",",
		";",
		":",
		".",
		"=>",
		"->",
		"comment",
	},
	Aliased: map[string]string{
		"!":   "unary_operator_literal",
		"!=":  "comparison_operator_literal",
		"%":   "arithmetic_operator_literal",
		"%=":  "assignment_operator_literal",
		"&":   "bitwise_operator_literal",
		"&=":  "assignment_operator_literal",
		"*":   "arithmetic_operator_literal",
		"*%":  "arithmetic_operator_literal",
		"*%=": "assignment_operator_literal",
		"*=":  "assignment_operator_literal",
		"+":   "arithmetic_operator_literal",
		"+%":  "arithmetic_operator_literal",
		"+%=": "assignment_operator_literal",
		"+=":  "assignment_operator_literal",
		"-":   "arithmetic_operator_literal",
		"-%":  "arithmetic_operator_literal",
		"-%=": "assignment_operator_literal",
		"-=":  "assignment_operator_literal",
		".*":  "unary_operator_literal",
		".?":  "unary_operator_literal",
		"/":   "arithmetic_operator_literal",
		"/=":  "assignment_operator_literal",
		"<":   "comparison_operator_literal",
		"<<":  "bitwise_operator_literal",
		"<<=": "assignment_operator_literal",
		"<=":  "comparison_operator_literal",
		"=":   "assignment_operator_literal",
		"==":  "comparison_operator_literal",
		">":   "comparison_operator_literal",
		">=":  "comparison_operator_literal",
		">>":  "bitwise_operator_literal",
		">>=": "assignment_operator_literal",
		"^":   "bitwise_operator_literal",
		"^=":  "assignment_operator_literal",
		"and": "logical_operator_literal",
		"or":  "logical_operator_literal",
		"|":   "bitwise_operator_literal",
		"|=":  "assignment_operator_literal",
		"~":   "bitwise_operator_literal",
	},
	Scaffolding: []string{
		"source_file",
		"block",
		"statement",
		"expression_statement",
		"function_declaration",
		"variable_declaration",
		"parameter",
		"parameters",
		"arguments",
		"struct_declaration",
		"enum_declaration",
		"union_declaration",
		"initializer_list",
		"struct_initializer",
		"anonymous_struct_initializer",
	},
	Keywords: []string{
		"fn",
		"const",
		"var",
		"pub",
		"export",
		"extern",
		"inline",
		"noinline",
		"comptime",
		"struct",
		"enum",
		"union",
		"error",
		"type",
		"void",
		"bool",
		"anytype",
		"if",
		"else",
		"switch",
		"while",
		"for",
		"return",
		"break",
		"continue",
		"defer",
		"errdefer",
		"try",
		"catch",
		"unreachable",
		"usingnamespace",
		"test",
	},
	Declarations: []string{
		"function_declaration",
		"variable_declaration",
		"struct_declaration",
		"enum_declaration",
		"union_declaration",
		"opaque_declaration",
		"error_set_declaration",
		"test_declaration",
		"using_namespace_declaration",
	},
	Identifiers: []string{
		"identifier",
	},
	Blocks: []string{
		"block",
	},
	Wrappers: []string{
		"parenthesized_expression",
		"array_type",
		"slice_type",
		"pointer_type",
		"initializer_list",
		"arguments",
		"parameters",
	},
	Pairs: []string{
		"field_initializer",
		"container_field",
	},
	EquivalentTypes: [][]string{
		{"struct_declaration", "enum_declaration", "union_declaration", "error_set_declaration", "opaque_declaration"},
		{"variable_declaration", "comptime_declaration"},
		{"for_statement", "while_statement"},
	},
	Comments: []string{
		"comment",
	},
	Calls: []string{
		"call_expression",
	},
}
